### ISSUE TITLE
boto version

### ISSUE THREAD

**Issue by mroswell** [nprapps/books15#102]
from requirements.txt: 
> boto==2.34.0

Boto2, at http://boto.cloudhackers.com/en/latest/ref/s3.html
is described as an "older version." They add:

> Boto3, the next version of Boto, is now stable and recommended for general use. 

The documentation points to 
https://github.com/boto/boto3

(I'm currently getting a mass of errors that seem to be related to S3 and boto, which is why I'm looking at this.)

**Comment by eads** [comment]
At the moment, we're still using Boto2. That shouldn't be the source of your problems.
